### PR TITLE
Locally abstract types

### LINKED ISSUE #15: Exclusions fail for locally abstract types
When using locally abstract types, the exclusions do not work. I have created a branch of this repo and added a (failing) testcase here:

https://github.com/rleonid/bisect_ppx/compare/rleonid:master...simonjbeaumont:locally-abstract-types

The preprocessor should not add instrumentation to this function since it matches the regexp in the `exclusions` file. However it does:

```
$ make -C tests one NAME=ppx-exclude-file
make: Entering directory `/local/work/code/bisect_ppx/tests'
Running tests for 'ppx-exclude-file'...
make[1]: Entering directory `/local/work/code/bisect_ppx/tests/ppx-exclude-file'
     testing 'source.ml' ...
Files source.ml.reference and source.ml.result differ
make[1]: *** [default] Error 1
make[1]: Leaving directory `/local/work/code/bisect_ppx/tests/ppx-exclude-file'
make: Leaving directory `/local/work/code/bisect_ppx/tests'
```

```diff
$ (cd tests/ppx-exclude-file; diff -u source.ml.reference source.ml.result)
--- source.ml.reference 2015-06-08 15:22:37.932377656 +0100
+++ source.ml.result    2015-06-08 15:27:43.124377656 +0100
@@ -4,4 +4,10 @@
   Bisect.Runtime.mark "source.ml" 1;
   for i = 1 to 5 do (Bisect.Runtime.mark "source.ml" 0; print_endline s) done
 let f2 b x = if b then x * x else x
-let f3 : 'a . 'a -> string= fun (type a) -> (fun _  -> "Hello" : a -> string)
+let f3 : 'a . 'a -> string=
+  Bisect.Runtime.mark "source.ml" 2;
+  fun
+  (type
+  a)
+  ->
+  ((fun _  -> "Hello") : a -> string)
```

I generated the additional code in the `.reference` file using the `(*BISECT-IGNORE-BEGIN/END*)` bracketing.

My motivation for this is my use of this extension with https://github.com/simonjbeaumont/ocaml-pci which uses ctypes to generate bindings and ctypes uses code of the above form. I want to exclude the generated code from my results.

I might take a look around the code when I get a change see if I can come up with a pull request but any pointers would be appreciated.

Thanks in advance!

### PR DESCRIPTION
**Pull request by rleonid**
I think that this fixes #15

### CODE REVIEW

File: src/syntax/instrumentPpx.ml [hunk 1]
```diff
@@ -336,7 +336,17 @@ class instrumenter = object (self)
                 | Ppat_var ident when Exclusions.contains
                       (ident.loc.Location.loc_start.Lexing.pos_fname)
                     ident.txt -> vb.pvb_expr
-                | _ -> wrap_func Common.Binding (self#expr vb.pvb_expr)})
+                | Ppat_constraint (p,_) ->
+                    begin
+                      match p.ppat_desc with
```
Comment (smondet) [inline src/syntax/instrumentPpx.ml]: For the “future”, can you add a comment telling what that `match` does?

Comment (rleonid) [inline src/syntax/instrumentPpx.ml]: Good idea.

**Comment by smondet** [comment]
:+1:
